// src/components/chat/chat.component.ts

import { Component, ChangeDetectionStrategy, inject, signal, ElementRef, viewChild, effect, OnDestroy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConversationService } from '../../services/conversation.service';
import { GeminiService } from '../../services/gemini.service';
import { SpeechService } from '../../services/speech.service';

@Component({
  selector: 'app-chat',
  imports: [CommonModule],
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChatComponent implements OnDestroy {
  conversationService = inject(ConversationService);
  geminiService = inject(GeminiService);
  speechService = inject(SpeechService);

  isProcessing = signal(false);

  chatContainer = viewChild<ElementRef>('chatContainer');
  
  isMicDisabled = computed(() => this.speechService.isListening() || this.speechService.isSpeaking() || this.isProcessing());
  micButtonIcon = computed(() => {
    if (this.speechService.isListening()) return 'fa-microphone-slash';
    if (this.speechService.isSpeaking() || this.isProcessing()) return 'fa-circle-stop';
    return 'fa-microphone';
  });
  micButtonHint = computed(() => {
    if (this.speechService.isListening()) return 'Listening...';
    if (this.speechService.isSpeaking()) return 'Herr Schmidt is speaking...';
    if (this.isProcessing()) return 'Thinking...';
    if (this.conversationService.state() === 'active') return 'Tap the microphone to speak';
    return '';
  });

  constructor() {
    effect(() => {
        // Auto-scroll to the bottom when messages change
        this.conversationService.activeConversation();
        this.scrollToBottom();
    });
  }

  ngOnDestroy(): void {
    this.speechService.stop();
  }

  private scrollToBottom(): void {
    setTimeout(() => {
        const container = this.chatContainer()?.nativeElement;
        if (container) {
            container.scrollTop = container.scrollHeight;
        }
    }, 100);
  }
  
  async startNewConversation(): Promise<void> {
    this.conversationService.startConversation();
    const initialGreeting = this.conversationService.activeConversation()[0]?.text;
    if (initialGreeting) {
      try {
        await this.speechService.speak(initialGreeting, 'de-DE');
      } catch (e) {
        console.error("Error speaking initial greeting:", e);
      }
    }
  }

  async handleMicClick(): Promise<void> {
    if (this.isMicDisabled()) {
        this.speechService.stop();
        return;
    }

    try {
        const userTranscript = await this.speechService.listen('de-DE');
        if (userTranscript) {
            this.processUserMessage(userTranscript);
        }
    } catch (e) {
        console.error('Error during listening:', e);
    }
  }

  private async processUserMessage(message: string): Promise<void> {
    this.isProcessing.set(true);
    
    // The service now handles streaming to the UI and returns the full response.
    const fullResponse = await this.conversationService.addUserMessage(message);

    this.isProcessing.set(false);

    if (fullResponse && this.conversationService.isConversationActive()) {
      try {
        await this.speechService.speak(fullResponse, 'de-DE');
      } catch (e) {
        console.error("Error speaking AI response:", e);
      }
    }
  }

  stopConversation(): void {
    this.speechService.stop();
    this.conversationService.stopConversation();
  }
}


<div class="flex flex-col h-[calc(100vh-180px)] max-w-4xl mx-auto bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl rounded-2xl shadow-2xl shadow-blue-100/50 dark:shadow-slate-950/50 overflow-hidden border border-slate-200 dark:border-slate-700">
  @switch (conversationService.state()) {
    @case ('idle') {
      <div class="flex flex-col items-center justify-center h-full p-8 text-center bg-gradient-to-b from-white to-blue-50 dark:from-slate-800 dark:to-slate-900">
        <div class="relative w-40 h-40 flex items-center justify-center mb-6">
          <div class="absolute inset-0 bg-gradient-to-br from-blue-400 to-indigo-500 rounded-full opacity-20 blur-2xl"></div>
          <div class="w-32 h-32 bg-white dark:bg-slate-700 rounded-full shadow-lg flex items-center justify-center">
             <i class="fas fa-microphone-alt text-6xl text-transparent bg-clip-text bg-gradient-to-br from-blue-500 to-indigo-600"></i>
          </div>
        </div>
        <h2 class="text-4xl font-extrabold mb-2 text-slate-900 dark:text-white">Ready to Speak German?</h2>
        <p class="text-slate-600 dark:text-slate-300 mb-8 max-w-md">
          Start a real-time voice conversation with Herr Schmidt, your personal AI German tutor.
        </p>
        <button (click)="startNewConversation()" class="bg-gradient-to-br from-blue-500 to-indigo-600 hover:from-blue-600 hover:to-indigo-700 text-white font-bold py-4 px-10 rounded-full text-lg transition-transform transform hover:scale-105 shadow-lg shadow-blue-500/30">
          <i class="fas fa-play mr-2"></i>
          Start Voice Session
        </button>
      </div>
    }
    @case ('analyzing') {
      <div class="flex flex-col items-center justify-center h-full p-8 text-center">
        <div class="animate-spin text-6xl text-blue-500 mb-6">
          <i class="fas fa-spinner"></i>
        </div>
        <h2 class="text-3xl font-bold mb-2">Analyzing Your Conversation...</h2>
        <p class="text-slate-600 dark:text-slate-300 max-w-md">
          Herr Schmidt is reviewing your chat to create a personalized performance report. This will just take a moment.
        </p>
      </div>
    }
    @case ('report_ready') {
       <div class="flex flex-col items-center justify-center h-full p-8 text-center">
        <div class="w-24 h-24 bg-green-100 dark:bg-green-900/50 rounded-full mb-6 shadow-lg flex items-center justify-center">
          <i class="fas fa-check-circle text-5xl text-green-500"></i>
        </div>
        <h2 class="text-3xl font-bold mb-2">Report Ready!</h2>
        <p class="text-slate-600 dark:text-slate-300 mb-6 max-w-md">
          Your conversation analysis is complete. Check the "Progress" tab to see your feedback and track your journey.
        </p>
        <button (click)="startNewConversation()" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-3 px-8 rounded-full text-lg transition-transform transform hover:scale-105 shadow-lg">
          <i class="fas fa-redo mr-2"></i>
          Start Another Session
        </button>
      </div>
    }
    @case ('active') {
      <!-- Chat Header -->
      <div class="p-3 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center bg-white/30 dark:bg-slate-800/30 flex-shrink-0">
          <div class="flex items-center space-x-3">
              <div class="relative">
                  <img class="w-11 h-11 rounded-full object-cover" src="https://picsum.photos/id/1005/100/100" alt="Herr Schmidt Avatar">
                  <span class="absolute bottom-0 right-0 block h-3 w-3 rounded-full bg-green-400 ring-2 ring-white dark:ring-slate-800"></span>
              </div>
              <div>
                  <h3 class="font-bold text-slate-900 dark:text-white">Herr Schmidt</h3>
                  <p class="text-sm text-slate-500 dark:text-slate-400">AI Language Tutor</p>
              </div>
          </div>
          <button (click)="stopConversation()" class="bg-red-100 text-red-600 hover:bg-red-200 dark:bg-red-900/50 dark:text-red-400 dark:hover:bg-red-900/80 font-semibold py-2 px-4 rounded-lg transition-colors text-sm">
              <i class="fas fa-stop mr-2"></i>
              End Session
          </button>
      </div>

      <!-- Transcript Area -->
      <div class="flex-grow p-6 overflow-y-auto" #chatContainer>
        <div class="flex flex-col space-y-4">
          @for (message of conversationService.activeConversation(); track $index) {
            <div class="flex items-end space-x-2" [class.justify-end]="message.role === 'user'" [class.flex-row-reverse]="message.role === 'user'" [class.space-x-reverse]="message.role === 'user'">
              <div class="w-8 h-8 rounded-full bg-slate-200 dark:bg-slate-600 flex-shrink-0">
                  @if (message.role === 'model') {
                    <img class="w-full h-full rounded-full object-cover" src="https://picsum.photos/id/1005/100/100" alt="Herr Schmidt Avatar">
                  }
              </div>
              <div
                class="max-w-xl px-4 py-3 rounded-2xl shadow-md"
                [class.bg-gradient-to-br]="message.role === 'user'"
                [class.from-blue-500]="message.role === 'user'"
                [class.to-indigo-600]="message.role === 'user'"
                [class.text-white]="message.role === 'user'"
                [class.rounded-br-none]="message.role === 'user'"

                [class.bg-slate-100]="message.role === 'model'"
                [class.dark:bg-slate-700]="message.role === 'model'"
                [class.text-slate-800]="message.role === 'model'"
                [class.dark:text-slate-200]="message.role === 'model'"
                [class.rounded-bl-none]="message.role === 'model'"
              >
                @if (message.text) {
                  <p class="text-base">{{ message.text }}</p>
                } @else {
                  <div class="flex items-center space-x-2">
                    <span class="typing-dot"></span>
                    <span class="typing-dot" style="animation-delay: 0.2s;"></span>
                    <span class="typing-dot" style="animation-delay: 0.4s;"></span>
                  </div>
                }
              </div>
            </div>
          }
        </div>
      </div>
      <!-- Voice Controls Area -->
      <div class="p-4 bg-white/50 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-700 backdrop-blur-sm flex flex-col items-center justify-center flex-shrink-0">
        <button 
            (click)="handleMicClick()" 
            [disabled]="isMicDisabled() && !speechService.isListening()"
            class="w-20 h-20 rounded-full flex items-center justify-center transition-all duration-300 ease-in-out text-white text-3xl shadow-lg transform hover:scale-110"
            [class.mic-listening]="speechService.isListening()"
            [class.mic-speaking]="speechService.isSpeaking() || isProcessing()"
            [class.bg-gradient-to-br]="!isMicDisabled()"
            [class.from-blue-500]="!isMicDisabled()"
            [class.to-indigo-600]="!isMicDisabled()"
            [class.hover:shadow-xl]="!isMicDisabled()"
            [class.hover:shadow-blue-500/40]="!isMicDisabled()"
            [class.bg-gradient-to-br]="speechService.isListening()"
            [class.from-red-500]="speechService.isListening()"
            [class.to-rose-600]="speechService.isListening()"
            [class.bg-slate-400]="isMicDisabled() && !speechService.isListening()"
            [class.dark:bg-slate-600]="isMicDisabled() && !speechService.isListening()"
            [class.cursor-pointer]="!isMicDisabled() || speechService.isListening()"
            [class.cursor-not-allowed]="isMicDisabled() && !speechService.isListening()"
        >
            <i class="fas" [class]="micButtonIcon()"></i>
        </button>
        <p class="mt-3 text-sm font-medium text-slate-600 dark:text-slate-300 min-h-[20px]">
            {{ micButtonHint() }}
        </p>
        
        @if (speechService.error() || geminiService.error()) {
            <p class="text-red-500 text-sm mt-2 text-center">{{ speechService.error() || geminiService.error() }}</p>
        }
      </div>
    }
  }
</div>

// src/components/Chat.tsx

import React, { useEffect, useRef, useState, useMemo } from 'react';
import { useAppContext } from '../context/AppContext';
import { useSpeech } from '../hooks/useSpeech';
import { ChatMessage } from '../models/conversation.model';

const TypingIndicator = () => (
  <div className="flex items-center space-x-1.5">
    <div className="typing-dot" style={{ animationDelay: '0s' }}></div>
    <div className="typing-dot" style={{ animationDelay: '0.2s' }}></div>
    <div className="typing-dot" style={{ animationDelay: '0.4s' }}></div>
  </div>
);

// FIX: Explicitly type ChatBubble as a React.FC to ensure special props like 'key' are handled correctly by TypeScript's JSX parser.
const ChatBubble: React.FC<{ msg: ChatMessage }> = ({ msg }) => {
  const isUser = msg.role === 'user';
  return (
    <div className={`flex items-end space-x-3 ${isUser ? 'justify-end' : ''}`}>
      {!isUser && (
        <div className="w-8 h-8 rounded-full bg-slate-200 dark:bg-slate-600 flex items-center justify-center font-bold text-slate-500 dark:text-slate-300 flex-shrink-0">
          <i className="fas fa-robot"></i>
        </div>
      )}
      <div className={`p-3 rounded-2xl max-w-sm md:max-w-md ${isUser ? 'bg-blue-500 text-white rounded-br-none' : 'bg-white dark:bg-slate-700 rounded-bl-none'}`}>
        {msg.text ? <p className="text-sm md:text-base leading-relaxed">{msg.text}</p> : <TypingIndicator />}
      </div>
    </div>
  );
};

export function Chat() {
  const { conversationState, activeConversation, startConversation, addUserMessage, stopConversation } = useAppContext();
  const { isListening, isSpeaking, listen, speak, stop } = useSpeech();
  const [isProcessing, setIsProcessing] = useState(false);
  const chatContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [activeConversation]);

  useEffect(() => {
    return () => stop();
  }, [stop]);

  const handleStart = async () => {
    startConversation();
    setTimeout(async () => {
      try {
        await speak('Hallo! Ich bin Herr Schmidt. Lass uns auf Deutsch sprechen. Wie geht es Ihnen heute?', 'de-DE');
      } catch (e) { console.error(e); }
    }, 100);
  };

  const handleMicClick = async () => {
    if (isListening || isSpeaking || isProcessing) {
      stop();
      return;
    }
    try {
      const transcript = await listen('de-DE');
      if (transcript) {
        setIsProcessing(true);
        const response = await addUserMessage(transcript);
        setIsProcessing(false);
        if (response) {
          await speak(response, 'de-DE');
        }
      }
    } catch (e) {
      console.error(e);
      setIsProcessing(false);
    }
  };

  const isMicDisabled = isListening || isSpeaking || isProcessing;
  const micButtonClass = useMemo(() => {
      if (isListening) return 'bg-red-500 mic-listening';
      if (isSpeaking) return 'bg-sky-500 mic-speaking';
      return 'bg-blue-500 hover:bg-blue-600';
  }, [isListening, isSpeaking]);

  const micButtonIcon = useMemo(() => {
    if (isListening) return 'fa-microphone-slash';
    if (isSpeaking || isProcessing) return 'fa-circle-stop';
    return 'fa-microphone';
  }, [isListening, isSpeaking, isProcessing]);

  const micButtonHint = useMemo(() => {
    if (isListening) return 'Listening...';
    if (isSpeaking) return 'Herr Schmidt is speaking...';
    if (isProcessing) return 'Thinking...';
    if (conversationState === 'active') return 'Tap the microphone to speak';
    return '';
  }, [isListening, isSpeaking, isProcessing, conversationState]);

  const renderContent = () => {
    switch (conversationState) {
      case 'idle':
      case 'report_ready':
        return (
          <div className="flex flex-col items-center justify-center h-full text-center p-6">
            <h2 className="text-2xl font-bold text-slate-800 dark:text-white mb-2">Ready to Practice?</h2>
            <p className="text-slate-600 dark:text-slate-300 mb-6">Start a new conversation to test your German speaking skills.</p>
            <button onClick={handleStart} className="px-8 py-3 bg-blue-500 text-white font-bold rounded-full hover:bg-blue-600 transition-transform transform hover:scale-105 duration-300 shadow-lg">
              Start New Conversation
            </button>
          </div>
        );
      case 'analyzing':
        return (
          <div className="flex flex-col items-center justify-center h-full text-center p-6">
            <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-500 rounded-full animate-spin mb-4"></div>
            <h2 className="text-xl font-semibold text-slate-700 dark:text-slate-200">Analyzing your conversation...</h2>
            <p className="text-slate-500 dark:text-slate-400">Please wait while I prepare your feedback.</p>
          </div>
        );
      case 'active':
        return (
          <>
            <div ref={chatContainerRef} className="flex-grow p-6 space-y-6 overflow-y-auto">
              {activeConversation.map((msg, index) => <ChatBubble key={index} msg={msg} />)}
            </div>
            <div className="p-4 border-t border-slate-200 dark:border-slate-700 bg-white/50 dark:bg-slate-800/50">
              <div className="flex flex-col items-center space-y-2">
                <button onClick={handleMicClick} disabled={isMicDisabled} className={`w-16 h-16 rounded-full text-white flex items-center justify-center text-2xl transition-all duration-300 shadow-lg ${micButtonClass}`}>
                  <i className={`fas ${micButtonIcon}`}></i>
                </button>
                <p className="text-sm text-slate-500 dark:text-slate-400 h-5">{micButtonHint}</p>
                <button onClick={() => stopConversation()} className="text-sm text-slate-500 hover:text-red-500 dark:hover:text-red-400 transition-colors">
                  End Conversation & Get Report
                </button>
              </div>
            </div>
          </>
        );
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-180px)] max-w-4xl mx-auto bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl rounded-2xl shadow-2xl shadow-blue-100/50 dark:shadow-slate-950/50 overflow-hidden border border-slate-200 dark:border-slate-700">
      {renderContent()}
    </div>
  );
}
