// src/components/progress/progress.component.ts

import { Component, ChangeDetectionStrategy, inject, signal, effect } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { ConversationService } from '../../services/conversation.service';
import { WritingService } from '../../services/writing.service';
import { ConversationReport } from '../../models/conversation.model';
import { WritingReport } from '../../models/writing.model';

type ProgressView = 'conversations' | 'writing';

@Component({
  selector: 'app-progress',
  imports: [CommonModule, DatePipe],
  templateUrl: './progress.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProgressComponent {
  conversationService = inject(ConversationService);
  writingService = inject(WritingService);
  
  progressView = signal<ProgressView>('conversations');
  
  selectedConversationReport = signal<ConversationReport | null>(null);
  selectedWritingReport = signal<WritingReport | null>(null);

  constructor() {
    // Auto-select the latest report when the component initializes or when a new report is generated
    effect(() => {
        if (this.conversationService.latestReport()) {
            this.selectedConversationReport.set(this.conversationService.latestReport());
            this.progressView.set('conversations');
        }
    });

    effect(() => {
        if (this.writingService.latestReport()) {
            this.selectedWritingReport.set(this.writingService.latestReport());
            this.progressView.set('writing');
        }
    });
  }

  selectConversationReport(report: ConversationReport): void {
    this.selectedConversationReport.set(report);
  }

  selectWritingReport(report: WritingReport): void {
    this.selectedWritingReport.set(report);
  }

  setView(view: ProgressView) {
    this.progressView.set(view);
  }
}


<div class="max-w-7xl mx-auto">
  <!-- Overall Progress Summary -->
  <div class="bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-6 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 mb-8 border border-slate-200 dark:border-slate-700">
    <h2 class="text-3xl font-bold mb-1 text-slate-900 dark:text-white">Your Progress Dashboard</h2>
    <p class="text-slate-500 dark:text-slate-400 mb-6">Ein Schritt nach dem anderen – you're doing great!</p>
    <div class="grid md:grid-cols-3 gap-6 text-center">
      <!-- Level -->
      <div class="bg-gradient-to-br from-blue-50 to-white dark:from-slate-700/50 dark:to-slate-800/50 p-6 rounded-xl border border-slate-200 dark:border-slate-700 transform transition-transform hover:scale-105 hover:shadow-xl hover:shadow-blue-100 dark:hover:shadow-slate-950">
        <div class="text-blue-500 text-4xl mb-3"><i class="fas fa-trophy"></i></div>
        <div class="text-lg font-semibold text-slate-600 dark:text-slate-300">Speaking Level</div>
        <div class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ conversationService.level().name }}</div>
        <div class="text-sm text-slate-500">Level {{ conversationService.level().number }}</div>
      </div>
      <!-- Average Score -->
      <div class="bg-gradient-to-br from-green-50 to-white dark:from-slate-700/50 dark:to-slate-800/50 p-6 rounded-xl border border-slate-200 dark:border-slate-700 transform transition-transform hover:scale-105 hover:shadow-xl hover:shadow-green-100 dark:hover:shadow-slate-950">
        <div class="text-green-500 text-4xl mb-3"><i class="fas fa-star-half-alt"></i></div>
        <div class="text-lg font-semibold text-slate-600 dark:text-slate-300">Average Score</div>
        <div class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ conversationService.averageScore() }} <span class="text-xl font-semibold">%</span></div>
        <div class="text-sm text-slate-500">Across all voice sessions</div>
      </div>
      <!-- Sessions Completed -->
      <div class="bg-gradient-to-br from-purple-50 to-white dark:from-slate-700/50 dark:to-slate-800/50 p-6 rounded-xl border border-slate-200 dark:border-slate-700 transform transition-transform hover:scale-105 hover:shadow-xl hover:shadow-purple-100 dark:hover:shadow-slate-950">
        <div class="text-purple-500 text-4xl mb-3"><i class="fas fa-tasks"></i></div>
        <div class="text-lg font-semibold text-slate-600 dark:text-slate-300">Total Activities</div>
        <div class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ conversationService.reports().length + writingService.reports().length }}</div>
        <div class="text-sm text-slate-500">Voice & Writing Sessions</div>
      </div>
    </div>
  </div>

  <!-- History Toggles -->
  <div class="mb-6 flex justify-center">
    <div class="bg-slate-200 dark:bg-slate-700 p-1 rounded-lg flex space-x-1">
      <button (click)="setView('conversations')" [class.bg-white]="progressView() === 'conversations'" [class.dark:bg-slate-800]="progressView() === 'conversations'" [class.text-slate-900]="progressView() === 'conversations'" [class.dark:text-white]="progressView() === 'conversations'" class="px-6 py-2 rounded-md font-semibold transition-all">Conversations</button>
      <button (click)="setView('writing')" [class.bg-white]="progressView() === 'writing'" [class.dark:bg-slate-800]="progressView() === 'writing'" [class.text-slate-900]="progressView() === 'writing'" [class.dark:text-white]="progressView() === 'writing'" class="px-6 py-2 rounded-md font-semibold transition-all">Writing</button>
    </div>
  </div>

  @if (progressView() === 'conversations') {
    <!-- Session History and Report Details -->
    <div class="grid lg:grid-cols-3 gap-8">
      <!-- History List -->
      <div class="lg:col-span-1 bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-4 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 border border-slate-200 dark:border-slate-700 h-fit">
        <h3 class="text-xl font-bold mb-4 px-2 text-slate-900 dark:text-white">Conversation History</h3>
        @if (conversationService.reports().length > 0) {
          <ul class="space-y-2 max-h-[60vh] overflow-y-auto pr-2">
            @for (report of conversationService.reports(); track report.id) {
              <li>
                <button (click)="selectConversationReport(report)" class="w-full text-left p-3 rounded-lg transition-all duration-200" [class.bg-blue-500]="selectedConversationReport()?.id === report.id" [class.text-white]="selectedConversationReport()?.id === report.id" [class.shadow-md]="selectedConversationReport()?.id === report.id" [class.shadow-blue-200]="selectedConversationReport()?.id === report.id" [class.hover:bg-slate-100]="selectedConversationReport()?.id !== report.id" [class.dark:hover:bg-slate-700/50]="selectedConversationReport()?.id !== report.id">
                  <div class="font-semibold">{{ report.date | date:'MMMM d, yyyy' }}</div>
                  <div class="text-sm" [class.text-blue-100]="selectedConversationReport()?.id === report.id" [class.text-slate-500]="selectedConversationReport()?.id !== report.id" [class.dark:text-slate-400]="selectedConversationReport()?.id !== report.id">{{ report.date | date:'h:mm a' }}</div>
                </button>
              </li>
            }
          </ul>
        } @else {
          <div class="text-center p-8 text-slate-500 dark:text-slate-400"><i class="fas fa-folder-open text-4xl mb-4"></i><p>Complete a chat session to see your analysis here!</p></div>
        }
      </div>

      <!-- Report Details -->
      <div class="lg:col-span-2">
        @if (selectedConversationReport(); as report) {
          <div class="bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-6 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 border border-slate-200 dark:border-slate-700 space-y-6">
             <!-- Content identical to previous version -->
            <div><h3 class="text-2xl font-bold text-slate-900 dark:text-white">Session Report</h3><p class="text-slate-500 dark:text-slate-400">Analysis from {{ report.date | date:'longDate' }}</p></div><div class="bg-slate-50 dark:bg-slate-900/40 p-5 rounded-xl border border-slate-200 dark:border-slate-700 space-y-4"><h4 class="font-bold text-lg text-slate-800 dark:text-slate-200">Performance Scores</h4><div><div class="flex justify-between mb-1"><span class="text-base font-medium text-blue-700 dark:text-blue-300">Grammar</span><span class="text-sm font-medium text-blue-700 dark:text-blue-300">{{ report.grammarScore }}%</span></div><div class="w-full bg-slate-200 rounded-full h-3 dark:bg-slate-700"><div class="bg-blue-600 h-3 rounded-full" [style.width.%]="report.grammarScore"></div></div></div><div><div class="flex justify-between mb-1"><span class="text-base font-medium text-green-700 dark:text-green-300">Vocabulary</span><span class="text-sm font-medium text-green-700 dark:text-green-300">{{ report.vocabularyScore }}%</span></div><div class="w-full bg-slate-200 rounded-full h-3 dark:bg-slate-700"><div class="bg-green-600 h-3 rounded-full" [style.width.%]="report.vocabularyScore"></div></div></div><div><div class="flex justify-between mb-1"><span class="text-base font-medium text-purple-700 dark:text-purple-300">Fluency</span><span class="text-sm font-medium text-purple-700 dark:text-purple-300">{{ report.fluencyScore }}%</span></div><div class="w-full bg-slate-200 rounded-full h-3 dark:bg-slate-700"><div class="bg-purple-600 h-3 rounded-full" [style.width.%]="report.fluencyScore"></div></div></div></div><div class="space-y-4"><div class="border-l-4 border-slate-400 bg-slate-50 dark:bg-slate-900/40 p-4 rounded-r-lg"><h4 class="font-bold text-lg mb-2 flex items-center text-slate-800 dark:text-slate-200"><i class="fas fa-comment-dots text-slate-500 mr-3"></i>Overall Feedback</h4><p class="text-slate-600 dark:text-slate-300">{{ report.overallFeedback }}</p></div><div class="border-l-4 border-green-500 bg-green-50 dark:bg-green-900/20 p-4 rounded-r-lg"><h4 class="font-bold text-lg mb-2 flex items-center text-green-800 dark:text-green-300"><i class="fas fa-thumbs-up mr-3"></i>What Went Well</h4><ul class="list-disc list-inside space-y-2 pl-2 text-slate-700 dark:text-slate-300">@for(point of report.positivePoints; track $index) { <li>{{ point }}</li> }</ul></div><div class="border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-r-lg"><h4 class="font-bold text-lg mb-2 flex items-center text-yellow-800 dark:text-yellow-300"><i class="fas fa-lightbulb mr-3"></i>Areas for Improvement</h4><ul class="list-disc list-inside space-y-2 pl-2 text-slate-700 dark:text-slate-300">@for(area of report.areasForImprovement; track $index) { <li>{{ area }}</li> }</ul></div></div>
          </div>
        } @else {
          <div class="flex flex-col items-center justify-center bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-6 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 border border-slate-200 dark:border-slate-700 min-h-[400px]"><i class="fas fa-file-alt text-6xl text-slate-400 dark:text-slate-500 mb-4"></i><h3 class="text-2xl font-bold">Select a Session</h3><p class="text-slate-500 dark:text-slate-400 mt-1 max-w-sm text-center">Choose a session from the history list to view the detailed report.</p></div>
        }
      </div>
    </div>
  } @else {
    <!-- Writing History and Report Details -->
    <div class="grid lg:grid-cols-3 gap-8">
      <!-- History List -->
      <div class="lg:col-span-1 bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-4 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 border border-slate-200 dark:border-slate-700 h-fit">
        <h3 class="text-xl font-bold mb-4 px-2 text-slate-900 dark:text-white">Writing History</h3>
        @if (writingService.reports().length > 0) {
          <ul class="space-y-2 max-h-[60vh] overflow-y-auto pr-2">
            @for (report of writingService.reports(); track report.id) {
              <li>
                <button (click)="selectWritingReport(report)" class="w-full text-left p-3 rounded-lg transition-all duration-200" [class.bg-blue-500]="selectedWritingReport()?.id === report.id" [class.text-white]="selectedWritingReport()?.id === report.id" [class.shadow-md]="selectedWritingReport()?.id === report.id" [class.shadow-blue-200]="selectedWritingReport()?.id === report.id" [class.hover:bg-slate-100]="selectedWritingReport()?.id !== report.id" [class.dark:hover:bg-slate-700/50]="selectedWritingReport()?.id !== report.id">
                  <div class="font-semibold">{{ report.date | date:'MMMM d, yyyy' }}</div>
                  <div class="text-sm" [class.text-blue-100]="selectedWritingReport()?.id === report.id" [class.text-slate-500]="selectedWritingReport()?.id !== report.id" [class.dark:text-slate-400]="selectedWritingReport()?.id !== report.id">{{ report.date | date:'h:mm a' }}</div>
                </button>
              </li>
            }
          </ul>
        } @else {
          <div class="text-center p-8 text-slate-500 dark:text-slate-400"><i class="fas fa-folder-open text-4xl mb-4"></i><p>Analyze your first writing sample to see your report here!</p></div>
        }
      </div>

      <!-- Report Details -->
      <div class="lg:col-span-2">
        @if (selectedWritingReport(); as report) {
          <div class="bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-6 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 border border-slate-200 dark:border-slate-700 space-y-6">
            <div class="grid md:grid-cols-2 gap-6">
                <div>
                    <h3 class="text-xl font-bold text-slate-900 dark:text-white mb-3">Your Submission</h3>
                    <img [src]="report.imageUrl" alt="Your handwriting" class="rounded-lg shadow-md border border-slate-200 dark:border-slate-700 w-full">
                </div>
                <div class="space-y-4">
                  <div class="border-l-4 border-slate-400 bg-slate-50 dark:bg-slate-900/40 p-4 rounded-r-lg h-full flex flex-col">
                    <h4 class="font-bold text-lg mb-2 flex items-center text-slate-800 dark:text-slate-200"><i class="fas fa-comment-dots text-slate-500 mr-3"></i>Overall Feedback</h4>
                    <p class="text-slate-600 dark:text-slate-300 flex-grow">{{ report.overallFeedback }}</p>
                  </div>
                </div>
            </div>
            <div class="border-l-4 border-green-500 bg-green-50 dark:bg-green-900/20 p-4 rounded-r-lg">
                <h4 class="font-bold text-lg mb-2 flex items-center text-green-800 dark:text-green-300"><i class="fas fa-thumbs-up mr-3"></i>What Went Well</h4>
                <ul class="list-disc list-inside space-y-2 pl-2 text-slate-700 dark:text-slate-300">
                  @for(point of report.positivePoints; track $index) { <li>{{ point }}</li> }
                </ul>
            </div>
            <div>
                <h3 class="font-bold text-xl mb-3 text-slate-900 dark:text-white">Corrections & Suggestions</h3>
                 <div class="border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-r-lg">
                    <ul class="space-y-4">
                      @for (correction of report.corrections; track $index) {
                        <li>
                          <p class="text-sm text-slate-600 dark:text-slate-400">You wrote: <s class="text-red-500/80">{{ correction.original }}</s></p>
                          <p class="text-base font-semibold text-green-700 dark:text-green-400">Suggestion: {{ correction.corrected }}</p>
                          <p class="text-sm text-slate-700 dark:text-slate-300 mt-1 pl-4 border-l-2 border-slate-300 dark:border-slate-600">{{ correction.explanation }}</p>
                        </li>
                      }
                    </ul>
                 </div>
            </div>
          </div>
        } @else {
          <div class="flex flex-col items-center justify-center bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl p-6 rounded-2xl shadow-lg shadow-blue-100/50 dark:shadow-slate-950/50 border border-slate-200 dark:border-slate-700 min-h-[400px]"><i class="fas fa-file-alt text-6xl text-slate-400 dark:text-slate-500 mb-4"></i><h3 class="text-2xl font-bold">Select a Writing Sample</h3><p class="text-slate-500 dark:text-slate-400 mt-1 max-w-sm text-center">Choose a sample from the history list to view the detailed report.</p></div>
        }
      </div>
    </div>
  }
</div>

// src/components/Progress.tsx

import React, { useState, useEffect, useMemo } from 'react';
import { useAppContext } from '../context/AppContext';
import { ConversationReport } from '../models/conversation.model';
import { WritingReport } from '../models/writing.model';

type ProgressView = 'conversations' | 'writing';

const ScoreGauge = ({ score, label }: { score: number, label: string }) => {
  const circumference = 2 * Math.PI * 45;
  const offset = circumference - (score / 100) * circumference;
  const colorClass = score >= 75 ? 'text-green-500' : score >= 50 ? 'text-yellow-500' : 'text-red-500';

  return (
    <div className="flex flex-col items-center">
      <div className="relative w-28 h-28">
        <svg className="w-full h-full" viewBox="0 0 100 100">
          <circle className="text-slate-200 dark:text-slate-700" strokeWidth="10" stroke="currentColor" fill="transparent" r="45" cx="50" cy="50" />
          <circle className={`${colorClass} transition-all duration-500 ease-in-out`} strokeWidth="10" strokeDasharray={circumference} strokeDashoffset={offset} strokeLinecap="round" stroke="currentColor" fill="transparent" r="45" cx="50" cy="50" transform="rotate(-90 50 50)" />
        </svg>
        <span className="absolute inset-0 flex items-center justify-center text-2xl font-bold">{score}</span>
      </div>
      <p className="mt-2 text-sm font-semibold text-slate-600 dark:text-slate-300">{label}</p>
    </div>
  );
};

export function Progress() {
  const { conversationReports, writingReports, latestConversationReport, latestWritingReport, averageScore, level } = useAppContext();
  const [progressView, setProgressView] = useState<ProgressView>('conversations');
  const [selectedConversation, setSelectedConversation] = useState<ConversationReport | null>(null);
  const [selectedWriting, setSelectedWriting] = useState<WritingReport | null>(null);
  
  const sortedConversationReports = useMemo(() => [...conversationReports].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime()), [conversationReports]);
  const sortedWritingReports = useMemo(() => [...writingReports].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime()), [writingReports]);

  useEffect(() => {
    if (latestConversationReport) {
      setSelectedConversation(latestConversationReport);
      setProgressView('conversations');
    } else if (sortedConversationReports.length > 0) {
      setSelectedConversation(sortedConversationReports[0]);
    }
  }, [latestConversationReport, sortedConversationReports]);
  
  useEffect(() => {
    if (latestWritingReport) {
      setSelectedWriting(latestWritingReport);
      setProgressView('writing');
    } else if (sortedWritingReports.length > 0) {
      setSelectedWriting(sortedWritingReports[0]);
    }
  }, [latestWritingReport, sortedWritingReports]);

  const formatDate = (date: Date) => new Date(date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const formatTime = (date: Date) => new Date(date).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });

  const renderConversationDetails = (report: ConversationReport) => (
    <div className="p-6">
      <h3 className="text-xl font-bold mb-4">Conversation Details</h3>
      <div className="grid grid-cols-3 gap-4 mb-6">
        <ScoreGauge score={report.grammarScore} label="Grammar" />
        <ScoreGauge score={report.vocabularyScore} label="Vocabulary" />
        <ScoreGauge score={report.fluencyScore} label="Fluency" />
      </div>
      <div className="space-y-4">
        <div>
          <h4 className="font-semibold mb-2">Overall Feedback</h4>
          <p className="text-slate-600 dark:text-slate-300">{report.overallFeedback}</p>
        </div>
        <div>
          <h4 className="font-semibold mb-2">Areas for Improvement</h4>
          <ul className="list-disc list-inside space-y-1 text-slate-600 dark:text-slate-300">
            {report.areasForImprovement.map((item, i) => <li key={i}>{item}</li>)}
          </ul>
        </div>
        <div>
          <h4 className="font-semibold mb-2">What You Did Well</h4>
          <ul className="list-disc list-inside space-y-1 text-slate-600 dark:text-slate-300">
            {report.positivePoints.map((item, i) => <li key={i}>{item}</li>)}
          </ul>
        </div>
      </div>
    </div>
  );
  
  const renderWritingDetails = (report: WritingReport) => (
      <div className="p-6">
          <h3 className="text-xl font-bold mb-4">Writing Details</h3>
          <img src={report.imageUrl} alt="Handwriting sample" className="rounded-lg mb-4" />
          <div>
            <h4 className="font-semibold mb-2">Overall Feedback</h4>
            <p className="text-slate-600 dark:text-slate-300 mb-4">{report.overallFeedback}</p>
          </div>
          <div>
            <h4 className="font-semibold mb-2">Corrections</h4>
            <div className="space-y-2">
                {report.corrections.map((c, i) => (
                    <div key={i} className="p-2 bg-slate-100 dark:bg-slate-700/50 rounded">
                        <p className="line-through text-red-500 text-sm">{c.original}</p>
                        <p className="text-green-600 font-medium text-sm">{c.corrected}</p>
                    </div>
                ))}
            </div>
          </div>
      </div>
  );
  
  const NoReports = ({ type }: {type: string}) => (
      <div className="flex flex-col items-center justify-center h-full text-center text-slate-500 p-8">
          <i className="fas fa-folder-open text-4xl mb-4"></i>
          <h3 className="font-semibold text-lg">No {type} Reports Yet</h3>
          <p className="text-sm">Complete a session to see your progress here.</p>
      </div>
  );

  return (
    <div className="max-w-7xl mx-auto animate-fade-in">
      <div className="p-6 bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl rounded-2xl shadow-lg border border-slate-200 dark:border-slate-700 mb-6 flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Your Progress</h2>
          <p className="text-slate-600 dark:text-slate-300">Level {level.number}: {level.name}</p>
        </div>
        <div className="text-right">
          <p className="text-4xl font-bold text-blue-500">{averageScore}<span className="text-xl text-slate-400">/100</span></p>
          <p className="text-sm text-slate-500">Avg. Conversation Score</p>
        </div>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl rounded-2xl shadow-lg border border-slate-200 dark:border-slate-700 overflow-hidden">
          <div className="p-4 border-b border-slate-200 dark:border-slate-700">
              <div className="flex bg-slate-100 dark:bg-slate-700 rounded-lg p-1">
                  <button onClick={() => setProgressView('conversations')} className={`w-1/2 py-2 text-sm font-semibold rounded-md transition-colors ${progressView === 'conversations' ? 'bg-white dark:bg-slate-600 shadow' : 'text-slate-600 dark:text-slate-300'}`}>Conversations</button>
                  <button onClick={() => setProgressView('writing')} className={`w-1/2 py-2 text-sm font-semibold rounded-md transition-colors ${progressView === 'writing' ? 'bg-white dark:bg-slate-600 shadow' : 'text-slate-600 dark:text-slate-300'}`}>Writing</button>
              </div>
          </div>
          <div className="h-[450px] overflow-y-auto">
              {progressView === 'conversations' && (
                  sortedConversationReports.length > 0 ? (
                      <ul>
                          {sortedConversationReports.map(report => (
                              <li key={report.id}>
                                  <button onClick={() => setSelectedConversation(report)} className={`w-full text-left p-4 border-b border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors ${selectedConversation?.id === report.id ? 'bg-blue-50 dark:bg-blue-900/20' : ''}`}>
                                      <p className="font-semibold">{formatDate(report.date)}</p>
                                      <p className="text-sm text-slate-500 dark:text-slate-400">{formatTime(report.date)}</p>
                                  </button>
                              </li>
                          ))}
                      </ul>
                  ) : <NoReports type="Conversation" />
              )}
              {progressView === 'writing' && (
                  sortedWritingReports.length > 0 ? (
                       <ul>
                          {sortedWritingReports.map(report => (
                              <li key={report.id}>
                                  <button onClick={() => setSelectedWriting(report)} className={`w-full text-left p-4 border-b border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors ${selectedWriting?.id === report.id ? 'bg-blue-50 dark:bg-blue-900/20' : ''}`}>
                                      <p className="font-semibold">{formatDate(report.date)}</p>
                                      <p className="text-sm text-slate-500 dark:text-slate-400">{formatTime(report.date)}</p>
                                  </button>
                              </li>
                          ))}
                      </ul>
                  ) : <NoReports type="Writing" />
              )}
          </div>
        </div>
        <div className="lg:col-span-2 bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl rounded-2xl shadow-lg border border-slate-200 dark:border-slate-700 overflow-hidden">
          <div className="h-[550px] overflow-y-auto">
            {progressView === 'conversations' && selectedConversation && renderConversationDetails(selectedConversation)}
            {progressView === 'writing' && selectedWriting && renderWritingDetails(selectedWriting)}
            {progressView === 'conversations' && !selectedConversation && <NoReports type="Conversation" />}
            {progressView === 'writing' && !selectedWriting && <NoReports type="Writing" />}
          </div>
        </div>
      </div>
    </div>
  );
}
